insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (1, 'M01', 'LWF Bloco de espuma', 'UTE-01');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (2, 'M02', 'LWF Bloco de espuma', 'UTE-01');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (3, 'M03', 'outros', 'UTE-01');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (4, 'M04', 'outros', 'UTE-01');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (5, 'M06', 'PUR Moldagem de espuma', 'UTE-02');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (6, 'M07', 'Moldagem de carpete', 'UTE-02');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (7, 'M08', 'Prensagem a quente', 'UTE-02');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (8, 'M09', 'Prensagem a quente', 'UTE-02');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (9, 'M10', 'Moldagem de espuma PUR', 'UTE-02');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (10, 'M11', 'Moldagem de espuma PUR', 'UTE-02');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (11, 'M12', 'Moldagem de espuma PUR', 'UTE-02');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (12, 'M13', 'Moldagem de espuma PUR', 'UTE-02');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (13, 'M14', 'Prensagem a quente', 'UTE-03');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (14, 'M15', 'Prensagem a quente', 'UTE-03');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (15, 'M16', 'Prensagem a quente', 'UTE-03');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (16, 'M17', 'outros', 'UTE-03');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (17, 'M18', 'outros', 'UTE-03');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (18, 'M19', 'Prensagem a quente', 'UTE-03');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (19, 'M20', 'Prensagem a quente', 'UTE-03');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (20, 'M21', 'Prensagem a quente', 'UTE-03');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (21, 'M22', 'Jato d''água', 'UTE-03');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (22, 'M23', 'Prensagem a quente', 'UTE-03');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (23, 'M24', 'Prensagem a quente', 'UTE-04');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (24, 'M25', 'Prensagem a quente', 'UTE-02');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (25, 'M26', 'Prensagem a quente', 'UTE-04');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (26, 'M27', 'outros', 'UTE-04');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (27, 'M28', 'Prensagem a quente', 'UTE-04');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (28, 'M29', 'Prensagem a quente', 'UTE-04');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (29, 'M30', 'Prensagem a quente', 'UTE-02');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (30, 'M31', 'outros', 'UTE-04');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (31, 'M32', 'Prensagem a quente', 'UTE-04');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (32, 'M33', 'Prensagem a quente', 'UTE-04');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (33, 'M34', 'Prensagem a quente', 'UTE-04');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (34, 'M35', 'Moldagem de carpete', 'UTE-05');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (35, 'M36', 'outros', 'UTE-05');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (36, 'M37', 'Moldagem de espuma PUR', 'UTE-05');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (37, 'M38', 'Moldagem de espuma PUR', 'UTE-05');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (38, 'M39', 'PUR Moldagem de espuma', 'UTE-05');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (39, 'M40', 'PUR Moldagem de espuma', 'UTE-05');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (40, 'M41', 'Jato d''água', 'UTE-05');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (41, 'M42', 'Jato d''água', 'UTE-05');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (42, 'M41 INTENSIFICADOR', 'outros', 'UTE-05');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (43, 'M41 WATER JET', 'outros', 'UTE-05');
insert into `Machine` (`id`, `tag`, `technology`, `ute`) values (44, 'M42 WATER JET', 'outros', 'UTE-05');
